//! Placing a raster image on a page as an image XObject (§8.9.5).
//!
//! ## What these tests are really checking, and why they read the BYTES
//!
//! An image placement is **four coordinated writes**: the image XObject, an
//! optional `/SMask`, a content stream that invokes it, and one patch to the
//! page dictionary carrying both `/Contents` and `/Resources`. Any three
//! without the fourth produce a document that is broken in a way nothing
//! reports — a page whose resources name an XObject its content never
//! invokes shows nothing at all, and every in-memory assertion about the
//! image still passes.
//!
//! Worse, the load-bearing property of this whole feature is a claim about
//! *bytes*: that a JPEG's codestream reaches the document **unchanged**, and
//! that a PNG's `IDAT` is reused verbatim under `/Predictor 15`. A model
//! that says "the image is there" cannot see a stream that holds the right
//! pixels behind the wrong filter, or the right filter over re-compressed
//! bytes. **R159** names exactly this: *"a defect that lives in the BYTES
//! must be asserted in the BYTES."*
//!
//! So the assertions here mostly run over the SAVED FILE, extracted with a
//! deliberately dumb scanner ([`object_body`], [`stream_payload`]) that does
//! no repair of its own — because a lenient parser is precisely what would
//! hide the failures this feature can have.
//!
//! ## Fixture provenance
//!
//! Every image under `fixtures/synthetic/images/` is generated by
//! `tools/gen-image-fixtures.py` from pixel data this project authored.
//! Nothing is downloaded (project rule 7, `LEGAL.md` §5). See that
//! directory's `PROVENANCE.md`.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use pdfce_core::document::Document;
use pdfce_core::edit::{EditError, EditSession, NewImage};
use pdfce_core::graph::ObjectGraph;
use pdfce_core::image_import::{
    self, ImageCompression, ImageImportError, ImportFilter, ImportOptions, ImportedImage,
    Orientation, PdfFeature, RecompressReason, SUPPORTED_FORMATS,
};
use pdfce_core::object::{Dict, Name, ObjId, Object};
use pdfce_core::page_tree::Rect;
use pdfce_core::writer::SaveOptions;
use std::path::{Path, PathBuf};

// ---------------------------------------------------------------------------
// Harness
// ---------------------------------------------------------------------------

fn fixture(rel: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/synthetic")
        .join(rel)
}

fn image_bytes(name: &str) -> Vec<u8> {
    std::fs::read(fixture(&format!("images/{name}")))
        .unwrap_or_else(|e| panic!("read fixture images/{name}: {e}"))
}

fn imported(name: &str) -> ImportedImage {
    image_import::import(&image_bytes(name)).unwrap_or_else(|e| panic!("import images/{name}: {e}"))
}

/// A 400 × 400 single-page document with an empty content stream.
fn session() -> EditSession {
    EditSession::new(Document::load(&fixture("dimension/plain-base.pdf")).expect("load fixture"))
}

fn rect(llx: f64, lly: f64, urx: f64, ury: f64) -> Rect {
    Rect { llx, lly, urx, ury }
}

/// Save incrementally and return the whole output file.
fn saved(s: &mut EditSession) -> Vec<u8> {
    s.to_incremental_bytes(&SaveOptions::identity())
        .expect("incremental save")
        .0
}

/// The body of indirect object `id` **as it appears in the saved bytes**.
///
/// Takes the LAST occurrence, because an incremental update appends a new
/// definition after the original and the newest one is what a reader
/// resolves. Deliberately a byte scan rather than a parse: this helper must
/// not be able to repair, normalise, or reinterpret anything on the way
/// in — that is the whole point of asserting here rather than on a model
/// (R159).
fn object_body(pdf: &[u8], id: u32) -> Vec<u8> {
    let needle = format!("\n{id} 0 obj");
    let start = pdf
        .windows(needle.len())
        .enumerate()
        .filter(|(_, w)| *w == needle.as_bytes())
        .map(|(i, _)| i + needle.len())
        .next_back()
        .unwrap_or_else(|| panic!("object {id} is not in the saved file"));
    let end = pdf
        .windows(6)
        .enumerate()
        .skip(start)
        .find(|(_, w)| *w == b"endobj")
        .map(|(i, _)| i)
        .unwrap_or_else(|| panic!("object {id} has no endobj"));
    pdf.get(start..end).unwrap_or_default().to_vec()
}

/// The raw stream payload inside an object body — between the EOL that
/// follows the `stream` keyword and the `endstream` that closes it
/// (§7.3.8.1).
fn stream_payload(body: &[u8]) -> Vec<u8> {
    let kw = b"stream";
    let at = body
        .windows(kw.len())
        .enumerate()
        .find(|(_, w)| *w == kw)
        .map(|(i, _)| i + kw.len())
        .expect("the object has a stream keyword");
    // "shall be followed by CRLF or LF alone, and NOT by CR alone".
    let start = if body.get(at) == Some(&b'\r') {
        at + 2
    } else {
        at + 1
    };
    let end = body
        .windows(9)
        .enumerate()
        .filter(|(_, w)| *w == b"endstream")
        .map(|(i, _)| i)
        .next_back()
        .expect("the object has an endstream");
    // There should be an EOL before `endstream` and it is not part of the
    // data, so trim exactly one.
    let mut stop = end;
    if body.get(stop.wrapping_sub(1)) == Some(&b'\n') {
        stop -= 1;
    }
    if body.get(stop.wrapping_sub(1)) == Some(&b'\r') {
        stop -= 1;
    }
    body.get(start..stop).unwrap_or_default().to_vec()
}

fn contains(hay: &[u8], needle: &[u8]) -> bool {
    hay.windows(needle.len()).any(|w| w == needle)
}

/// A one-page document at an arbitrary declared version, with a real
/// §7.5.4 cross-reference table.
///
/// Written byte by byte with computed offsets rather than by any PDF
/// library — the same discipline the fixture generators follow, so the file
/// cannot inherit a normalization from the code under test. Offsets are
/// derived from the emitted bytes, so the table is correct by construction
/// rather than by a hand count that rots when a byte changes.
fn minimal_pdf(version: &str) -> Vec<u8> {
    let bodies = [
        "<< /Type /Catalog /Pages 2 0 R >>",
        "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] /Resources << >> >>",
    ];
    let mut out = format!("%PDF-{version}\n%\u{e2}\u{e3}\u{cf}\u{d3}\n").into_bytes();
    let mut offsets = Vec::new();
    for (i, body) in bodies.iter().enumerate() {
        offsets.push(out.len());
        out.extend_from_slice(format!("{} 0 obj\n{body}\nendobj\n", i + 1).as_bytes());
    }
    let startxref = out.len();
    out.extend_from_slice(b"xref\n0 4\n0000000000 65535 f \n");
    for off in &offsets {
        out.extend_from_slice(format!("{off:010} 00000 n \n").as_bytes());
    }
    out.extend_from_slice(b"trailer\n<< /Size 4 /Root 1 0 R >>\nstartxref\n");
    out.extend_from_slice(format!("{startxref}\n%%EOF\n").as_bytes());
    out
}

/// The image XObject dictionary as the RELOADED document sees it — the
/// other half of the R159 pairing: the bytes say one thing, and a fresh
/// parse of those bytes must agree.
fn reloaded_image(pdf: &[u8], id: ObjId) -> (Document, Dict, Vec<u8>) {
    let doc = Document::from_bytes(pdf.to_vec()).expect("the saved file reloads");
    let (dict, raw) = {
        let obj = doc.get(id).expect("the image object survives a reload");
        let Object::Stream(stream) = &obj.value else {
            panic!("the image object is not a stream");
        };
        let raw = doc
            .view()
            .slice(stream.data_span)
            .expect("the stream's bytes are addressable")
            .to_vec();
        (stream.dict.clone(), raw)
    };
    (doc, dict, raw)
}

fn dict_int(d: &Dict, key: &[u8]) -> Option<i64> {
    d.get(key).and_then(Object::as_int)
}

fn dict_name(d: &Dict, key: &[u8]) -> Option<Vec<u8>> {
    d.get(key)
        .and_then(Object::as_name)
        .map(|n| n.as_bytes().to_vec())
}

/// The `/XObject` subdictionary the page's resources end up with.
fn page_xobjects(s: &EditSession, page_index: usize) -> Dict {
    let graph = s.graph();
    let page = s.pages().expect("pages")[page_index].id;
    let dict = graph.resolved(page).as_dict().expect("page dict").clone();
    let res = graph
        .resolve(dict.get(b"Resources").expect("page has /Resources"))
        .as_dict()
        .expect("/Resources is a dictionary")
        .clone();
    graph
        .resolve(res.get(b"XObject").expect("/Resources has /XObject"))
        .as_dict()
        .expect("/XObject is a dictionary")
        .clone()
}

// ---------------------------------------------------------------------------
// THE headline: bytes in, same bytes out
// ---------------------------------------------------------------------------

/// A JPEG's codestream reaches the document **byte-identical**, behind
/// `/DCTDecode`, with no `/DecodeParms` and no `/Decode`.
///
/// This is the single most important assertion in the file. A re-encode
/// would still produce a working document with a plausible-looking image —
/// it would simply be a slightly worse copy, every time, invisibly. Only a
/// byte comparison catches it.
#[test]
fn a_jpegs_bytes_survive_byte_identical_into_dctdecode() {
    let source = image_bytes("rgb.jpg");
    let img = image_import::import(&source).unwrap();
    assert_eq!(img.filter, ImportFilter::DctDecode);

    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(50.0, 50.0, 200.0, 200.0), &img))
        .expect("place the JPEG");
    let pdf = saved(&mut s);

    let body = object_body(&pdf, out.image_id.num);
    assert_eq!(
        stream_payload(&body),
        source,
        "the /DCTDecode stream IS the source file, not a re-encoding of it"
    );
    assert!(contains(&body, b"/Filter /DCTDecode"), "{body:?}");
    assert!(
        !contains(&body, b"/DecodeParms"),
        "Table 13 makes the codestream's APP14 marker outrank /ColorTransform, \
         so writing the entry could only agree redundantly or disagree wrongly"
    );
    assert!(
        !contains(&body, b"/Decode ["),
        "R29: /Decode is never written on import — it is the sole polarity \
         control and pdfce has no polarity opinion to record"
    );

    // …and a fresh parse of those bytes agrees.
    let (_doc, dict, raw) = reloaded_image(&pdf, out.image_id);
    assert_eq!(raw, source);
    assert_eq!(dict_name(&dict, b"Subtype").as_deref(), Some(&b"Image"[..]));
    assert_eq!(
        dict_name(&dict, b"ColorSpace").as_deref(),
        Some(&b"DeviceRGB"[..])
    );
    assert_eq!(dict_int(&dict, b"BitsPerComponent"), Some(8));
    assert_eq!(dict_int(&dict, b"Width"), Some(6));
    assert_eq!(dict_int(&dict, b"Height"), Some(4));
    assert_eq!(
        dict_int(&dict, b"Length"),
        Some(i64::try_from(source.len()).unwrap()),
        "§7.3.8 Table 5: /Length counts the bytes between `stream` and `endstream`"
    );
}

/// A non-interlaced PNG's `IDAT` payload is reused verbatim as a
/// `/FlateDecode` stream under `/Predictor 15` — no inflate, no re-deflate,
/// no arithmetic at all.
#[test]
fn a_pngs_idat_is_reused_verbatim_under_predictor_15() {
    let source = image_bytes("rgb8.png");
    let idat = extract_idat(&source);
    let img = image_import::import(&source).unwrap();

    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 120.0, 80.0), &img))
        .expect("place the PNG");
    let pdf = saved(&mut s);

    let body = object_body(&pdf, out.image_id.num);
    assert_eq!(
        stream_payload(&body),
        idat,
        "the /FlateDecode stream IS the source IDAT"
    );
    assert!(contains(&body, b"/Filter /FlateDecode"));
    for parm in [
        &b"/Predictor 15"[..],
        b"/Colors 3",
        b"/BitsPerComponent 8",
        b"/Columns 6",
    ] {
        assert!(
            contains(&body, parm),
            "Table 8 parameter {} is required for correctness, not decoration",
            String::from_utf8_lossy(parm)
        );
    }
    assert!(img.notes.recompressed.is_none());
}

/// The passthrough is not merely byte-equal — it **decodes to the right
/// pixels through pdfce's own filter stack**. A `/Predictor 15` stream that
/// happened to be byte-equal to the IDAT while describing the wrong row
/// geometry would pass the previous test and produce noise here.
#[test]
fn the_passthrough_stream_decodes_to_the_original_pixels() {
    let source = image_bytes("rgb8.png");
    let img = image_import::import(&source).unwrap();
    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 120.0, 80.0), &img))
        .unwrap();
    let pdf = saved(&mut s);
    let (_doc, dict, raw) = reloaded_image(&pdf, out.image_id);

    let samples = pdfce_core::filters::decode_stream(&dict, &raw).expect("the stream decodes");
    // 6 × 4 RGB at 8 bits = 18 bytes per row, 4 rows.
    assert_eq!(samples.len(), 6 * 4 * 3);
    // The generator's ramp: red goes 0 → 255 across the row, blue is its
    // complement, green goes 0 → 255 down the column. Row 0 (the TOP row,
    // §8.9.4) therefore has green = 0.
    assert_eq!(samples.get(0..3), Some(&[0u8, 0, 255][..]), "top-left");
    assert_eq!(samples.get(15..18), Some(&[255u8, 0, 0][..]), "top-right");
    // Last row: green = 255.
    let last = samples.len() - 3;
    assert_eq!(
        samples.get(last..),
        Some(&[255u8, 255, 0][..]),
        "bottom-right"
    );
}

fn extract_idat(png: &[u8]) -> Vec<u8> {
    let mut out = Vec::new();
    let mut i = 8;
    while i + 8 <= png.len() {
        let len = u32::from_be_bytes(png.get(i..i + 4).unwrap().try_into().unwrap()) as usize;
        if png.get(i + 4..i + 8) == Some(b"IDAT") {
            out.extend_from_slice(png.get(i + 8..i + 8 + len).unwrap());
        }
        i += 12 + len;
    }
    out
}

// ---------------------------------------------------------------------------
// Transparency
// ---------------------------------------------------------------------------

/// A PNG's alpha channel becomes a real `/SMask` image — not a flattened
/// composite against white, and not a dropped channel.
#[test]
fn a_pngs_alpha_becomes_an_smask() {
    let img = imported("rgba8.png");
    assert_eq!(img.notes.recompressed, Some(RecompressReason::AlphaSplit));

    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(10.0, 10.0, 130.0, 90.0), &img))
        .expect("place the transparent PNG");
    let smask_id = out.soft_mask_id.expect("an /SMask object was created");
    let pdf = saved(&mut s);

    // The image dictionary points at it, in the BYTES.
    let body = object_body(&pdf, out.image_id.num);
    assert!(
        contains(&body, format!("/SMask {} 0 R", smask_id.num).as_bytes()),
        "{}",
        String::from_utf8_lossy(&body)
    );

    // And the mask itself is a DeviceGray image of the same size.
    let (_doc, mask, raw) = reloaded_image(&pdf, smask_id);
    assert_eq!(dict_name(&mask, b"Subtype").as_deref(), Some(&b"Image"[..]));
    assert_eq!(
        dict_name(&mask, b"ColorSpace").as_deref(),
        Some(&b"DeviceGray"[..]),
        "a soft mask carries opacity, which has one component"
    );
    assert_eq!(dict_int(&mask, b"Width"), dict_int(&mask, b"Width"));
    assert_eq!(dict_int(&mask, b"Width"), Some(6));
    assert_eq!(dict_int(&mask, b"Height"), Some(4));
    assert!(
        mask.get(b"Mask").is_none() && mask.get(b"SMask").is_none(),
        "the conservative shape: a soft mask has no mask of its own"
    );
    let alpha = pdfce_core::filters::decode_stream(&mask, &raw).unwrap();
    assert_eq!(alpha.len(), 6 * 4);
    assert_eq!(alpha.first(), Some(&0), "the generator's ramp starts at 0");
    assert_eq!(alpha.last(), Some(&255), "…and ends at 255");

    // The disclosures the operator is owed.
    assert!(out.disclosures.soft_mask_written);
    assert!(
        out.disclosures.transparency_not_previewed,
        "pdfce-render does not composite /SMask yet, and an operator who sees \
         an opaque preview must be told that is pdfce's gap, not a lost channel"
    );
}

/// A single transparent colour becomes a colour-key `/Mask` array — and the
/// image data still passes through verbatim, which is the whole reason this
/// case is handled separately from an alpha channel.
#[test]
fn a_single_transparent_colour_becomes_a_colour_key_mask() {
    let source = image_bytes("rgb-trns.png");
    let img = image_import::import(&source).unwrap();
    assert!(img.notes.transparent_colour_to_mask);

    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    assert!(
        out.soft_mask_id.is_none(),
        "no second image object is needed"
    );
    assert!(out.disclosures.colour_key_mask_written);

    let pdf = saved(&mut s);
    let body = object_body(&pdf, out.image_id.num);
    assert!(
        contains(&body, b"/Mask [0 0 0 0 255 255]"),
        "§8.9.6.4 wants [min1 max1 … minn maxn] in SOURCE sample space: {}",
        String::from_utf8_lossy(&body)
    );
    assert_eq!(
        stream_payload(&body),
        extract_idat(&source),
        "transparency did not cost the passthrough"
    );
}

/// Palette transparency keeps the indexed image verbatim and derives only
/// the mask — the branch that would be easy to collapse into "alpha always
/// means decode everything".
#[test]
fn palette_transparency_keeps_the_indexed_image_verbatim() {
    let source = image_bytes("indexed-trns.png");
    let img = image_import::import(&source).unwrap();
    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    let pdf = saved(&mut s);

    let body = object_body(&pdf, out.image_id.num);
    assert_eq!(stream_payload(&body), extract_idat(&source));
    assert!(out.soft_mask_id.is_some());
    assert!(img.notes.palette_alpha_to_soft_mask);
    assert!(img.notes.recompressed.is_none());
}

/// An indexed PNG lands as `[/Indexed /DeviceRGB hival <lookup>]` with the
/// lookup as a byte string (§8.6.6.3 permits a stream *or* a string, and a
/// ≤768-byte table does not deserve its own object).
#[test]
fn an_indexed_png_writes_an_indexed_colour_space() {
    let img = imported("indexed8.png");
    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    let pdf = saved(&mut s);
    let body = object_body(&pdf, out.image_id.num);
    assert!(
        contains(&body, b"/ColorSpace [/Indexed /DeviceRGB 5 <"),
        "the lookup rides inline as a byte string (§8.6.6.3 permits a stream \
         OR a string, and a 18-byte table does not deserve its own object): {}",
        String::from_utf8_lossy(&body)
    );
    assert!(
        contains(&body, b"/Colors 1"),
        "an Indexed image has ONE component — the index — however many the \
         base space has"
    );
}

// ---------------------------------------------------------------------------
// Placement geometry
// ---------------------------------------------------------------------------

/// `Stretch` honours the rectangle exactly and produces §8.9.4's own
/// `w 0 0 h x y cm` form.
#[test]
fn stretch_places_the_image_in_exactly_the_rectangle_asked_for() {
    let img = imported("rgb8.png");
    let mut s = session();
    let r = rect(100.0, 200.0, 250.0, 280.0);
    let out = s
        .add_image(&NewImage::new(0, r, &img).stretching())
        .unwrap();
    assert_eq!(out.placed_rect, r);

    let pdf = saved(&mut s);
    let content = stream_payload(&object_body(&pdf, out.content_id.num));
    let text = String::from_utf8_lossy(&content).to_string();
    assert!(
        text.contains("150 0 0 80 100 200 cm"),
        "§8.9.4's own example form — width, height, then the lower-left \
         corner: {text}"
    );
    assert!(
        text.contains(&format!(
            "/{} Do",
            String::from_utf8_lossy(&out.resource_name)
        )),
        "{text}"
    );
    assert!(
        text.starts_with('q') && text.trim_end().ends_with('Q'),
        "§8.4: q/Q shall be balanced, and the image's CTM must not leak into \
         whatever the page draws next: {text}"
    );
    // 6 px across 150 pt = 2.88 dpi.
    assert!(
        out.disclosures.aspect_distorted,
        "6:4 stretched into 150:80"
    );
    assert!(out.disclosures.below_screen_resolution);
}

/// `Contain` — the default — preserves the aspect ratio and centres, and
/// says so.
#[test]
fn contain_preserves_the_aspect_ratio_and_centres() {
    let img = imported("rgb8.png"); // 6 × 4, aspect 1.5
    let mut s = session();
    // A 300 × 100 box: height is the binding constraint, so the image is
    // 150 × 100 and gets 75 points of slack on each side.
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 300.0, 100.0), &img))
        .unwrap();
    let p = out.placed_rect;
    assert!((p.llx - 75.0).abs() < 1e-9, "{p:?}");
    assert!((p.urx - 225.0).abs() < 1e-9, "{p:?}");
    assert!((p.lly - 0.0).abs() < 1e-9, "{p:?}");
    assert!((p.ury - 100.0).abs() < 1e-9, "{p:?}");
    assert!(out.disclosures.letterboxed);
    assert!(!out.disclosures.aspect_distorted);

    let pdf = saved(&mut s);
    let content = stream_payload(&object_body(&pdf, out.content_id.num));
    assert!(
        contains(&content, b"150 0 0 100 75 0 cm"),
        "{}",
        String::from_utf8_lossy(&content)
    );
}

/// A rectangle that already matches the aspect ratio is NOT reported as
/// letterboxed — a disclosure that fires on every placement is a
/// disclosure nobody reads.
#[test]
fn a_matching_rectangle_reports_no_letterboxing() {
    let img = imported("rgb8.png");
    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 150.0, 100.0), &img))
        .unwrap();
    assert!(!out.disclosures.letterboxed);
    assert!(!out.disclosures.any() || out.disclosures.below_screen_resolution);
}

/// An EXIF orientation is applied to the PLACEMENT MATRIX, and the
/// codestream is still verbatim. A rotate-90 photograph must come out
/// upright without a single pixel being re-encoded.
#[test]
fn an_exif_orientation_turns_the_placement_not_the_pixels() {
    let source = image_bytes("exif-rot90.jpg");
    let img = image_import::import(&source).unwrap();
    assert_eq!(img.orientation, Orientation::Rotate90);
    assert_eq!(
        img.display_size_px(),
        (4, 6),
        "a stored 6 × 4 turned 90° displays as 4 × 6"
    );

    let mut s = session();
    // A square box: `Contain` fits the DISPLAYED 4 × 6 shape, so the result
    // is taller than wide.
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 120.0, 120.0), &img))
        .unwrap();
    let p = out.placed_rect;
    assert!((p.urx - p.llx - 80.0).abs() < 1e-9, "{p:?}");
    assert!((p.ury - p.lly - 120.0).abs() < 1e-9, "{p:?}");
    assert_eq!(out.disclosures.exif_orientation_applied, Some(6));

    let pdf = saved(&mut s);
    assert_eq!(
        stream_payload(&object_body(&pdf, out.image_id.num)),
        source,
        "the rotation cost nothing — the codestream is untouched"
    );
    let content = stream_payload(&object_body(&pdf, out.content_id.num));
    // O6 = [0 -1 1 0 0 1]; w = 80, h = 120, origin (20, 0).
    //   a = 0·80 = 0     b = -1·120 = -120   c = 1·80 = 80
    //   d = 0·120 = 0    e = 0·80 + 20 = 20  f = 1·120 + 0 = 120
    assert!(
        contains(&content, b"0 -120 80 0 20 120 cm"),
        "{}",
        String::from_utf8_lossy(&content)
    );
}

/// A rectangle with no area is refused rather than producing a singular
/// transform every reader resolves differently.
#[test]
fn a_degenerate_rectangle_is_refused() {
    let img = imported("rgb8.png");
    let mut s = session();
    for r in [rect(10.0, 10.0, 10.0, 50.0), rect(10.0, 10.0, 50.0, 10.0)] {
        assert!(matches!(
            s.add_image(&NewImage::new(0, r, &img)),
            Err(EditError::ImageRectDegenerate { .. })
        ));
    }
    assert!(!s.is_modified(), "a refusal changes nothing");
}

#[test]
fn a_page_out_of_range_is_refused_by_index() {
    let img = imported("rgb8.png");
    let mut s = session();
    assert!(matches!(
        s.add_image(&NewImage::new(7, rect(0.0, 0.0, 10.0, 10.0), &img)),
        Err(EditError::PageOutOfRange { index: 7, count: 1 })
    ));
}

// ---------------------------------------------------------------------------
// Document wiring, round trip, undo
// ---------------------------------------------------------------------------

/// All four writes land: the resource names the image, the content invokes
/// that name, and the page's ORIGINAL content stream is still listed and
/// still byte-identical.
///
/// The third clause is R46: a feature that adds page content must not
/// rewrite the content that was already there.
#[test]
fn the_image_is_named_invoked_and_the_original_content_is_untouched() {
    let before = std::fs::read(fixture("dimension/plain-base.pdf")).unwrap();
    let img = imported("rgb8.png");
    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();

    // The name is in the page's effective /Resources /XObject…
    let xobj = page_xobjects(&s, 0);
    assert_eq!(
        xobj.get(out.resource_name.as_slice())
            .and_then(Object::as_reference),
        Some(out.image_id),
        "the resource entry points at the image object"
    );

    let pdf = saved(&mut s);
    // …the content stream invokes exactly that name…
    let content = stream_payload(&object_body(&pdf, out.content_id.num));
    assert!(contains(
        &content,
        &[b"/", out.resource_name.as_slice(), b" Do"].concat()
    ));

    // …the page's /Contents lists BOTH streams, in order…
    let page_body = object_body(&pdf, 3);
    assert!(
        contains(
            &page_body,
            format!("/Contents [4 0 R {} 0 R]", out.content_id.num).as_bytes()
        ),
        "the overlay is APPENDED, so it draws on top of what was there: {}",
        String::from_utf8_lossy(&page_body)
    );

    // …and the original content stream object is byte-identical, because
    // the incremental save never re-emitted it (R46, ARCHITECTURE.md §5).
    assert_eq!(
        pdf.get(..before.len()),
        Some(before.as_slice()),
        "an incremental save appends; it never rewrites the input prefix"
    );
    assert!(
        !contains(pdf.get(before.len()..).unwrap_or_default(), b"\n4 0 obj"),
        "object 4 — the page's original content stream — was not touched, so \
         it must not appear in the update section at all"
    );
}

/// The saved file reloads, the image decodes through pdfce's ordinary image
/// pipeline, and the samples are the ones that went in. This is the
/// end-to-end round trip: file → import → place → save → reload → decode.
#[test]
fn the_document_round_trips_and_the_image_decodes() {
    for name in [
        "rgb8.png",
        "gray8.png",
        "indexed8.png",
        "indexed4.png",
        "gray16.png",
        "rgb.jpg",
        "gray.jpg",
        "progressive.jpg",
        "rgb24.bmp",
        "pal8.bmp",
        "topdown24.bmp",
        "rgba8.png",
        "graya8.png",
    ] {
        let img = imported(name);
        let mut s = session();
        let out = s
            .add_image(&NewImage::new(0, rect(0.0, 0.0, 120.0, 80.0), &img))
            .unwrap_or_else(|e| panic!("{name}: {e}"));
        let pdf = saved(&mut s);
        let (doc, dict, raw) = reloaded_image(&pdf, out.image_id);

        let coded = pdfce_core::image_codec::decode_image(&doc, &dict, &raw, false)
            .unwrap_or_else(|e| panic!("{name} does not decode after a round trip: {e}"));
        assert_eq!(coded.width, img.width, "{name} width");
        assert_eq!(coded.height, img.height, "{name} height");
    }
}

/// Undo removes every trace, and re-saving reproduces the input byte for
/// byte — the property §11.1's diff-against-base design exists to give.
#[test]
fn undoing_a_placement_reproduces_the_input_byte_for_byte() {
    let before = std::fs::read(fixture("dimension/plain-base.pdf")).unwrap();
    let img = imported("rgba8.png");
    let mut s = session();
    s.add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    assert!(s.is_modified());

    assert!(s.undo().is_some(), "one placement is ONE undo entry");
    assert!(
        !s.is_modified(),
        "the image XObject, the /SMask, the content stream and BOTH page-dict \
         patches undo together — a partial undo would leave a page naming an \
         object that no longer exists"
    );
    assert_eq!(saved(&mut s), before);

    // …and redo puts it back.
    assert!(s.redo().is_some());
    assert!(s.is_modified());
}

/// Two images on one page get distinct resource names and both survive —
/// the second must not shadow the first.
#[test]
fn two_images_on_one_page_get_distinct_names() {
    let a = imported("rgb8.png");
    let b = imported("gray8.png");
    let mut s = session();
    let first = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &a))
        .unwrap();
    let second = s
        .add_image(&NewImage::new(0, rect(100.0, 0.0, 160.0, 40.0), &b))
        .unwrap();
    assert_ne!(first.resource_name, second.resource_name);

    let xobj = page_xobjects(&s, 0);
    assert_eq!(
        xobj.get(first.resource_name.as_slice())
            .and_then(Object::as_reference),
        Some(first.image_id)
    );
    assert_eq!(
        xobj.get(second.resource_name.as_slice())
            .and_then(Object::as_reference),
        Some(second.image_id)
    );

    let pdf = saved(&mut s);
    let page_body = object_body(&pdf, 3);
    assert!(
        contains(&page_body, b"/Contents [4 0 R "),
        "both overlays are appended to the ONE /Contents array: {}",
        String::from_utf8_lossy(&page_body)
    );
}

/// A page whose `/Resources` are inherited must get its OWN, so the
/// addition does not leak the image into every sibling page (§7.7.3.4).
#[test]
fn an_inherited_resource_dictionary_is_materialised_onto_the_page() {
    let doc = Document::load(&fixture("addtext/inherited-resources.pdf")).expect("fixture");
    let mut s = EditSession::new(doc);
    let img = imported("rgb8.png");
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    let xobj = page_xobjects(&s, 0);
    assert_eq!(
        xobj.get(out.resource_name.as_slice())
            .and_then(Object::as_reference),
        Some(out.image_id)
    );
}

// ---------------------------------------------------------------------------
// Refusals — every one by name, with the working formats named too
// ---------------------------------------------------------------------------

/// A format pdfce does not place is refused by NAME, and the message says
/// which formats do work. A silent failure, or a wrong-looking placement,
/// would both be worse.
#[test]
fn an_unsupported_format_refuses_by_name() {
    for (bytes, format) in [
        (b"GIF89a\x01\x00\x01\x00".to_vec(), "GIF"),
        (b"II\x2a\x00\x08\x00\x00\x00".to_vec(), "TIFF"),
        (b"RIFF\x00\x00\x00\x00WEBPVP8 ".to_vec(), "WebP"),
    ] {
        let err = image_import::import(&bytes).unwrap_err();
        assert_eq!(err, ImageImportError::UnsupportedFormat { format });
        let msg = err.to_string();
        assert!(msg.contains(format), "{msg}");
        assert!(msg.contains(SUPPORTED_FORMATS), "{msg}");
    }

    let err = image_import::import(&image_bytes("not-an-image.bin")).unwrap_err();
    assert_eq!(err, ImageImportError::NotAnImage);
    assert!(err.to_string().contains(SUPPORTED_FORMATS));
}

/// Sub-features of supported formats are refused with a stable key, so a
/// front end can explain the specific thing rather than "could not read
/// image".
#[test]
fn unsupported_sub_features_refuse_with_a_stable_key() {
    for (file, feature) in [
        ("interlaced.png", "PNG/interlaced"),
        ("arithmetic.jpg", "JPEG/arithmetic"),
        ("rle8.bmp", "BMP/rle8"),
    ] {
        assert_eq!(
            image_import::import(&image_bytes(file)).unwrap_err(),
            ImageImportError::Unsupported { feature },
            "{file}"
        );
    }
}

// ---------------------------------------------------------------------------
// Disclosures
// ---------------------------------------------------------------------------

/// R30's shape, mirrored onto the write direction: a CMYK JPEG whose
/// polarity nothing declares is embedded unchanged (R29) and NAMED.
#[test]
fn a_cmyk_jpeg_is_embedded_unchanged_and_its_polarity_is_named() {
    let source = image_bytes("cmyk.jpg");
    let img = image_import::import(&source).unwrap();
    assert!(img.notes.cmyk_polarity_unverifiable);

    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    assert!(out.disclosures.cmyk_polarity_unverifiable);

    let pdf = saved(&mut s);
    let body = object_body(&pdf, out.image_id.num);
    assert_eq!(stream_payload(&body), source);
    assert!(contains(&body, b"/ColorSpace /DeviceCMYK"));
    assert!(
        !contains(&body, b"/Decode"),
        "R29: no inversion, ever, on any branch"
    );
}

/// A BMP always reports that it was re-compressed, and a 32-bit one reports
/// that its fourth byte was ignored.
#[test]
fn a_bmp_discloses_its_recompression_and_its_ignored_fourth_byte() {
    let img = imported("rgb32.bmp");
    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    assert_eq!(
        out.disclosures.recompressed,
        Some(RecompressReason::NoCompressedSource)
    );
    assert!(out.disclosures.bmp_fourth_byte_ignored);
    assert!(!out.disclosures.soft_mask_written, "BI_RGB has no alpha");
}

/// A feature newer than the document's own version is disclosed rather than
/// silently upgrading `%PDF-x.y`.
#[test]
fn a_feature_newer_than_the_document_is_disclosed() {
    // A minimal PDF 1.3 document — old enough that a 16-bit image (PDF 1.5)
    // is ahead of it. Built with a real §7.5.4 cross-reference table rather
    // than left for the recovery path, because a RECOVERED base refuses an
    // incremental save (and rightly so), and the header check below has to
    // run over an incremental output.
    let doc = Document::from_bytes(minimal_pdf("1.3")).expect("a valid 1.3 document");
    let mut s = EditSession::new(doc);
    let img = imported("gray16.png");
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    let (feature, doc_version) = out
        .disclosures
        .version_ahead_of_document
        .expect("16 bpc is a PDF 1.5 feature in a PDF 1.3 file");
    assert_eq!(feature, PdfFeature::BitsPerComponent16);
    assert_eq!(doc_version.major, 1);
    assert_eq!(doc_version.minor, 3);

    // …and the header is NOT rewritten.
    let pdf = saved(&mut s);
    assert!(pdf.starts_with(b"%PDF-1.3"), "the header is left alone");
}

/// The same image in a modern document reports nothing about versions —
/// the disclosure fires on a real mismatch, not on the feature's existence.
#[test]
fn a_modern_document_reports_no_version_mismatch() {
    let img = imported("gray16.png");
    let mut s = session(); // %PDF-1.7
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    assert!(out.disclosures.version_ahead_of_document.is_none());
}

/// The effective resolution is reported as a number, and the
/// below-72-dpi flag fires only when the image is genuinely being enlarged
/// past its own resolution.
#[test]
fn the_effective_resolution_is_reported() {
    let img = imported("rgb8.png"); // 6 × 4 px
    let mut s = session();
    // 6 px across 6 points = 72 dpi exactly.
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 6.0, 4.0), &img).stretching())
        .unwrap();
    let (dx, dy) = out.disclosures.effective_dpi;
    assert!((dx - 72.0).abs() < 1e-9, "{dx}");
    assert!((dy - 72.0).abs() < 1e-9, "{dy}");
    assert!(!out.disclosures.below_screen_resolution);

    // Twice the size is half the resolution.
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 12.0, 8.0), &img).stretching())
        .unwrap();
    assert!((out.disclosures.effective_dpi.0 - 36.0).abs() < 1e-9);
    assert!(out.disclosures.below_screen_resolution);
}

/// A tagged document is disclosed: pdfce writes no structure element for
/// the image, so it has no alternate text and assistive technology cannot
/// describe it.
#[test]
fn a_tagged_document_is_disclosed() {
    let doc = Document::load(&fixture("addtext/tagged.pdf")).expect("fixture");
    let mut s = EditSession::new(doc);
    let img = imported("rgb8.png");
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    assert!(out.disclosures.tagged_document);
    assert!(out.disclosures.any());
}

/// A certified document refuses placement by name — placing an image
/// changes what the page renders, so it takes the strict gate.
#[test]
fn a_certified_document_refuses_placement() {
    let doc = Document::load(&fixture("addtext/certified-locked.pdf")).expect("fixture");
    let mut s = EditSession::new(doc);
    let img = imported("rgb8.png");
    assert!(matches!(
        s.add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img)),
        Err(EditError::CertificationForbidsChange { .. })
    ));
    assert!(!s.is_modified());
}

/// `any()` must answer for every field. A disclosure struct that grows a
/// field the summary predicate forgets is a disclosure that silently stops
/// being shown — so the two are pinned together here.
#[test]
fn an_ordinary_placement_with_nothing_to_say_says_nothing() {
    let img = imported("rgb8.png");
    let mut s = session();
    // Exactly 72 dpi, exact aspect ratio, no transparency, no profile, a
    // modern untagged document: there is genuinely nothing to disclose.
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 6.0, 4.0), &img))
        .unwrap();
    assert!(
        !out.disclosures.any(),
        "nothing was inferred, so nothing is claimed: {:?}",
        out.disclosures
    );
}

/// Every fixture in the corpus either imports or refuses by name — never a
/// panic, never a generic failure. The cheapest possible guard against a
/// parser that walks off the end of a real file.
#[test]
fn every_fixture_either_imports_or_refuses_by_name() {
    let dir = fixture("images");
    let mut seen = 0usize;
    for entry in std::fs::read_dir(&dir).expect("the fixture directory exists") {
        let path = entry.expect("dir entry").path();
        let bytes = std::fs::read(&path).expect("read fixture");
        seen += 1;
        match image_import::import(&bytes) {
            Ok(img) => {
                assert!(img.width > 0 && img.height > 0, "{path:?}");
                assert!(!img.data.is_empty(), "{path:?}");
            }
            Err(
                ImageImportError::Unsupported { .. }
                | ImageImportError::UnsupportedFormat { .. }
                | ImageImportError::NotAnImage,
            ) => {}
            Err(other) => panic!("{path:?} failed unhelpfully: {other}"),
        }
    }
    assert!(
        seen >= 20,
        "the fixture corpus shrank unexpectedly ({seen})"
    );
}

/// The names pdfce gives its own resources are recognisable in the saved
/// file — a small thing, but it is what lets a later Pass (or a human
/// reading the PDF) tell pdfce's additions from the producer's.
#[test]
fn authored_resources_carry_the_pdfce_prefix() {
    let img = imported("rgb8.png");
    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    assert!(
        out.resource_name.starts_with(b"pdfceIm"),
        "{:?}",
        String::from_utf8_lossy(&out.resource_name)
    );
    let _ = Name::from(out.resource_name.as_slice());
}

// ---------------------------------------------------------------------------
// Compression policy (per image; operator request, 2026-08-08)
// ---------------------------------------------------------------------------

fn imported_as(name: &str, compression: ImageCompression) -> ImportedImage {
    let options = ImportOptions::new().with_compression(compression);
    image_import::import_with(&image_bytes(name), &options)
        .unwrap_or_else(|e| panic!("import images/{name}: {e}"))
}

/// The default is passthrough, and the default is what an operator who says
/// nothing gets. Pinned as its own test because a default that quietly
/// changed would degrade every image in every document with no diff to read.
#[test]
fn the_default_policy_is_passthrough() {
    let img = imported("rgb.jpg");
    assert_eq!(
        img.notes.requested_compression,
        ImageCompression::Passthrough
    );
    assert_eq!(img.notes.applied_compression, ImageCompression::Passthrough);
    assert_eq!(img.data, image_bytes("rgb.jpg"));
    assert_eq!(ImportOptions::new(), ImportOptions::default());
}

/// `Lossless` on a JPEG is the ONE combination that changes the bytes: the
/// codestream is decoded and its samples stored as `/FlateDecode`.
#[test]
fn lossless_on_a_jpeg_decodes_and_stores_the_samples() {
    let img = imported_as("rgb.jpg", ImageCompression::Lossless);
    assert_eq!(img.filter, ImportFilter::Flate);
    assert_eq!(
        img.notes.recompressed,
        Some(RecompressReason::LosslessRequested)
    );
    assert_eq!(img.notes.applied_compression, ImageCompression::Lossless);
    assert!(
        img.notes.lossless_from_lossy,
        "the operator must be told that this recovers nothing"
    );
    assert_ne!(img.data, image_bytes("rgb.jpg"), "the bytes changed");

    // The stream really is the decoded samples: 6 x 4 RGB at 8 bits.
    let samples = pdfce_core::filters::flate::decode(&img.data, None).unwrap();
    assert_eq!(samples.len(), 6 * 4 * 3);

    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    assert!(out.disclosures.lossless_from_lossy);
    assert_eq!(
        out.disclosures.applied_compression,
        ImageCompression::Lossless
    );
    let pdf = saved(&mut s);
    let body = object_body(&pdf, out.image_id.num);
    assert!(contains(&body, b"/Filter /FlateDecode"), "{body:?}");
    assert!(!contains(&body, b"DCTDecode"));
}

/// A CMYK JPEG stored losslessly keeps `DeviceCMYK` and is still NOT
/// inverted (R29) — the decode path applies the Table 13 / TN #5116 §13.1
/// transform and nothing else, so the lossless branch cannot become a back
/// door for the polarity flip decision 006 forbids.
#[test]
fn lossless_on_a_cmyk_jpeg_keeps_devicecmyk_and_does_not_invert() {
    let img = imported_as("cmyk.jpg", ImageCompression::Lossless);
    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    let pdf = saved(&mut s);
    let body = object_body(&pdf, out.image_id.num);
    assert!(contains(&body, b"/ColorSpace /DeviceCMYK"), "{body:?}");
    assert!(
        !contains(&body, b"/Decode"),
        "R29 holds on every branch, including this one"
    );
    let samples = pdfce_core::filters::flate::decode(&img.data, None).unwrap();
    assert_eq!(samples.len(), 6 * 4 * 4, "four components per sample");
}

/// `Lossless` on a source that was ALREADY lossless keeps the source's own
/// bytes and reports the substitution. Re-deflating identical pixels is
/// strictly worse than not doing it, and silently doing the worse thing
/// because it matched the word the operator typed would be the wrong kind of
/// literal-mindedness.
#[test]
fn lossless_on_an_already_lossless_source_keeps_the_original_bytes() {
    let img = imported_as("rgb8.png", ImageCompression::Lossless);
    assert_eq!(img.data, extract_idat(&image_bytes("rgb8.png")));
    assert_eq!(img.notes.requested_compression, ImageCompression::Lossless);
    assert_eq!(
        img.notes.applied_compression,
        ImageCompression::Passthrough,
        "applied == Passthrough means, and only means, that the source's own \
         compressed bytes are in the document unchanged"
    );

    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &img))
        .unwrap();
    assert_ne!(
        out.disclosures.requested_compression,
        out.disclosures.applied_compression
    );
    assert!(
        out.disclosures.any(),
        "a substituted policy is always worth saying"
    );
}

/// `Passthrough` on a format with nothing to pass through reports the
/// substitution in the other direction.
#[test]
fn passthrough_on_a_bmp_reports_that_it_could_not_happen() {
    let img = imported("rgb24.bmp");
    assert_eq!(
        img.notes.requested_compression,
        ImageCompression::Passthrough
    );
    assert_eq!(
        img.notes.applied_compression,
        ImageCompression::Lossless,
        "a BMP stores no compressed bytes, so there was nothing to keep"
    );
    assert!(
        !img.notes.lossless_from_lossy,
        "a BMP is not a lossy source"
    );
}

/// A PNG whose alpha forced a split is reported as `Lossless`, not
/// `Passthrough` — the requested policy could not be honoured literally even
/// though nothing was degraded.
#[test]
fn a_split_alpha_png_reports_lossless_rather_than_passthrough() {
    let img = imported("rgba8.png");
    assert_eq!(img.notes.applied_compression, ImageCompression::Lossless);
    assert_eq!(img.notes.recompressed, Some(RecompressReason::AlphaSplit));
    assert!(!img.notes.lossless_from_lossy);
}

/// The JPEG re-encode policy refuses BY NAME, before the file is even
/// parsed, and names the policies that do work.
#[test]
fn the_jpeg_policy_refuses_by_name_because_there_is_no_encoder() {
    for name in ["rgb.jpg", "rgb8.png", "rgb24.bmp"] {
        let options = ImportOptions::new().with_compression(ImageCompression::Jpeg { quality: 85 });
        let err = image_import::import_with(&image_bytes(name), &options).unwrap_err();
        assert_eq!(
            err,
            ImageImportError::CompressionUnavailable { policy: "jpeg" },
            "{name}"
        );
        let msg = err.to_string();
        assert!(msg.contains("passthrough"), "{msg}");
        assert!(msg.contains("lossless"), "{msg}");
        assert!(msg.contains("no image encoder"), "{msg}");
    }

    // Refused even for bytes that are not an image at all — the policy is
    // checked first, so the operator learns the real blocker rather than a
    // second-order complaint about the file.
    let options = ImportOptions::new().with_compression(ImageCompression::Jpeg { quality: 1 });
    assert_eq!(
        image_import::import_with(b"not an image", &options).unwrap_err(),
        ImageImportError::CompressionUnavailable { policy: "jpeg" }
    );
}

/// The policy is per image, not global: two policies in one session land two
/// differently-stored images on the same page.
#[test]
fn two_images_on_one_page_can_use_different_policies() {
    let verbatim = imported("rgb.jpg");
    let lossless = imported_as("rgb.jpg", ImageCompression::Lossless);
    let mut s = session();
    let a = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &verbatim))
        .unwrap();
    let b = s
        .add_image(&NewImage::new(0, rect(100.0, 0.0, 160.0, 40.0), &lossless))
        .unwrap();
    let pdf = saved(&mut s);
    assert!(contains(
        &object_body(&pdf, a.image_id.num),
        b"/Filter /DCTDecode"
    ));
    assert!(contains(
        &object_body(&pdf, b.image_id.num),
        b"/Filter /FlateDecode"
    ));
    assert_eq!(
        stream_payload(&object_body(&pdf, a.image_id.num)),
        image_bytes("rgb.jpg"),
        "the passthrough placement is unaffected by the other one's policy"
    );
}

/// Every policy key round-trips as the stable string the CLI prints.
#[test]
fn policy_keys_are_stable() {
    assert_eq!(ImageCompression::Passthrough.key(), "passthrough");
    assert_eq!(ImageCompression::Lossless.key(), "lossless");
    assert_eq!(ImageCompression::Jpeg { quality: 85 }.key(), "jpeg");
    assert_eq!(RecompressReason::AlphaSplit.key(), "alpha-split");
    assert_eq!(
        RecompressReason::NoCompressedSource.key(),
        "no-compressed-source"
    );
    assert_eq!(
        RecompressReason::LosslessRequested.key(),
        "lossless-requested"
    );
}

/// The strongest available check that `Lossless` did not mangle anything:
/// for every JPEG in the corpus, the samples it stores must be **identical**
/// to what the passthrough placement decodes to through pdfce's ordinary
/// image pipeline.
///
/// Both paths run the same codec, so any difference means `to_lossless`
/// mis-sized a buffer, transposed a stride, or picked the wrong colour
/// space — none of which any structural assertion would catch, and all of
/// which look like a corrupted picture rather than an error.
#[test]
fn lossless_stores_exactly_what_the_passthrough_placement_decodes_to() {
    for name in ["rgb.jpg", "gray.jpg", "progressive.jpg", "cmyk.jpg"] {
        // The passthrough placement, decoded back out of a saved document.
        let verbatim = imported(name);
        let mut s = session();
        let out = s
            .add_image(&NewImage::new(0, rect(0.0, 0.0, 60.0, 40.0), &verbatim))
            .unwrap();
        let pdf = saved(&mut s);
        let (doc, dict, raw) = reloaded_image(&pdf, out.image_id);
        let through_pdf = pdfce_core::image_codec::decode_image(&doc, &dict, &raw, false)
            .unwrap_or_else(|e| panic!("{name}: {e}"));

        // The lossless import, un-deflated.
        let lossless = imported_as(name, ImageCompression::Lossless);
        let stored = pdfce_core::filters::flate::decode(&lossless.data, None).unwrap();

        assert_eq!(
            stored, through_pdf.samples,
            "{name}: lossless storage must hold exactly the pixels the \
             passthrough placement renders from"
        );
        assert_eq!(lossless.width, through_pdf.width, "{name} width");
        assert_eq!(lossless.height, through_pdf.height, "{name} height");
        assert_eq!(
            lossless.bits_per_component, through_pdf.bits_per_component,
            "{name} bit depth"
        );
    }
}

/// An EXIF orientation survives the lossless path — it is a property of the
/// picture, not of how the picture is stored, and losing it there would
/// rotate the image only for operators who chose lossless.
#[test]
fn lossless_keeps_the_exif_orientation() {
    let img = imported_as("exif-rot90.jpg", ImageCompression::Lossless);
    assert_eq!(img.orientation, Orientation::Rotate90);
    assert_eq!(img.notes.exif_orientation, Some(6));
    let mut s = session();
    let out = s
        .add_image(&NewImage::new(0, rect(0.0, 0.0, 120.0, 120.0), &img))
        .unwrap();
    assert_eq!(out.disclosures.exif_orientation_applied, Some(6));
    let p = out.placed_rect;
    assert!(
        (p.urx - p.llx - 80.0).abs() < 1e-9 && (p.ury - p.lly - 120.0).abs() < 1e-9,
        "the DISPLAYED 4x6 shape still drives the fit: {p:?}"
    );
}
