//! # Pass A (decision 013) — classic-`xref` EOL correctness, end to end
//!
//! Positive controls proving pdfce-core's classic cross-reference-table
//! parser (`xref::load_xref_chain`, and the whole `Document::from_bytes`
//! stack above it) accepts every end-of-line form ISO 32000-1 §7.5.4 and
//! §7.5.1 permit. This is the evidence behind decision 013's Pass A
//! conclusion: because the parser is demonstrably EOL-correct here, the
//! real-world CRLF-correlated load failures in the acquired corpus are
//! offset-shift corruption (stale stored offsets from LF->CRLF byte
//! growth), a rebuild-by-scan job for Pass B — not a parser bug.
//!
//! Each fixture in `fixtures/synthetic/xref-eol/` (provenance: that
//! directory's `PROVENANCE.md`, generated by `tools/gen-xref-eol-fixtures.py`)
//! is a complete, well-formed single-revision one-page document whose
//! classic table exercises one EOL dimension:
//!
//! - `entry-{spcr,splf,crlf}.pdf` — the three legal 2-byte entry EOLs
//!   `SP CR` / `SP LF` / `CR LF` (§7.5.4).
//! - `struct-{cr,crlf}.pdf`, `bare-cr-oldmac.pdf` — structural-line EOL
//!   tolerance (§7.5.1's CR / LF / CR LF fallback on the `xref`/header/
//!   `trailer`/`startxref` lines), including an old-Mac bare-CR file.
//! - `trailing-space.pdf` — incidental trailing SPACE before a header EOL.
//! - `multi-subsection.pdf` — non-contiguous, out-of-order subsections
//!   (subsection-relative object addressing, not a single `0 N`).
//! - `mixed-eol.pdf` — entries and structural lines that rotate through
//!   all legal forms, proving no uniform-EOL assumption anywhere.
//!
//! Every fixture must load: 4 in-use objects (1 catalog, 1 page tree, 1
//! page, 1 content stream), a 5-entry xref table (objects 0..=4, object 0
//! being the free-list head), and a resolvable `/Root` catalog.

use std::path::{Path, PathBuf};

use pdfce_core::document::Document;
use pdfce_core::object::Object;
use pdfce_core::xref;

/// A fixture path under `fixtures/synthetic/xref-eol/`.
fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/synthetic/xref-eol")
        .join(name)
}

fn bytes(name: &str) -> Vec<u8> {
    std::fs::read(fixture(name)).expect("fixture readable")
}

/// The shared contract every well-formed fixture must satisfy: the xref
/// layer sees all five entries, and the document layer resolves a proper
/// catalog with four in-use objects.
fn assert_loads_cleanly(name: &str) {
    let raw = bytes(name);

    // xref layer: 5 merged entries (objects 0..=4), object 0 free-list head.
    let loaded = xref::load_xref_chain(&raw)
        .unwrap_or_else(|e| panic!("{name}: xref chain failed to load: {e}"));
    assert_eq!(
        loaded.table.len(),
        5,
        "{name}: expected 5 xref entries (objects 0..=4)"
    );
    assert!(
        matches!(loaded.table.get(0), Some(xref::XrefEntry::Free { .. })),
        "{name}: object 0 must be the free-list head"
    );
    for num in 1..=4 {
        assert!(
            matches!(loaded.table.get(num), Some(xref::XrefEntry::InUse { .. })),
            "{name}: object {num} must be an in-use entry"
        );
    }

    // document layer: catalog resolves through /Root, page tree reachable.
    let doc = Document::from_bytes(raw)
        .unwrap_or_else(|e| panic!("{name}: Document::from_bytes failed: {e}"));
    assert_eq!(doc.object_count(), 4, "{name}: expected 4 in-use objects");
    let catalog = doc
        .catalog()
        .unwrap_or_else(|e| panic!("{name}: catalog unresolvable: {e}"));
    assert_eq!(
        catalog
            .get(b"Type")
            .and_then(Object::as_name)
            .map(|n| n.as_bytes()),
        Some(&b"Catalog"[..]),
        "{name}: /Root does not resolve to a /Catalog"
    );
    // /Pages must resolve to the page tree with /Count 1.
    let pages = catalog
        .get(b"Pages")
        .map(|p| doc.resolve(p))
        .and_then(Object::as_dict)
        .unwrap_or_else(|| panic!("{name}: /Pages unresolvable"));
    assert_eq!(
        pages.get(b"Count").and_then(Object::as_int),
        Some(1),
        "{name}: page tree /Count is not 1"
    );
}

#[test]
fn entry_eol_sp_cr_loads() {
    assert_loads_cleanly("entry-spcr.pdf");
}

#[test]
fn entry_eol_sp_lf_loads() {
    assert_loads_cleanly("entry-splf.pdf");
}

#[test]
fn entry_eol_cr_lf_loads() {
    assert_loads_cleanly("entry-crlf.pdf");
}

#[test]
fn structural_lines_bare_cr_loads() {
    assert_loads_cleanly("struct-cr.pdf");
}

#[test]
fn structural_lines_crlf_loads() {
    assert_loads_cleanly("struct-crlf.pdf");
}

#[test]
fn multi_subsection_out_of_order_loads() {
    assert_loads_cleanly("multi-subsection.pdf");
}

#[test]
fn trailing_space_before_header_eol_loads() {
    assert_loads_cleanly("trailing-space.pdf");
}

#[test]
fn old_mac_bare_cr_everywhere_loads() {
    assert_loads_cleanly("bare-cr-oldmac.pdf");
}

#[test]
fn mixed_eol_forms_load() {
    assert_loads_cleanly("mixed-eol.pdf");
}
