//! # Pass A (decision 013) — classic-`xref` EOL correctness, end to end
//!
//! Positive controls proving pdfce-core's classic cross-reference-table
//! parser (`xref::load_xref_chain`, and the whole `Document::from_bytes`
//! stack above it) accepts every end-of-line form ISO 32000-1 §7.5.4 and
//! §7.5.1 permit. This is the evidence behind decision 013's Pass A
//! conclusion: because the parser is demonstrably EOL-correct here, the
//! real-world CRLF-correlated load failures in the acquired corpus are
//! offset-shift corruption (stale stored offsets from LF->CRLF byte
//! growth), a rebuild-by-scan job for Pass B — not a parser bug.
//!
//! Each fixture in `fixtures/synthetic/xref-eol/` (provenance: that
//! directory's `PROVENANCE.md`, generated by `tools/gen-xref-eol-fixtures.py`)
//! is a complete, well-formed single-revision one-page document whose
//! classic table exercises one EOL dimension:
//!
//! - `entry-{spcr,splf,crlf}.pdf` — the three legal 2-byte entry EOLs
//!   `SP CR` / `SP LF` / `CR LF` (§7.5.4).
//! - `struct-{cr,crlf}.pdf`, `bare-cr-oldmac.pdf` — structural-line EOL
//!   tolerance (§7.5.1's CR / LF / CR LF fallback on the `xref`/header/
//!   `trailer`/`startxref` lines), including an old-Mac bare-CR file.
//! - `trailing-space.pdf` — incidental trailing SPACE before a header EOL.
//! - `multi-subsection.pdf` — non-contiguous, out-of-order subsections
//!   (subsection-relative object addressing, not a single `0 N`).
//! - `mixed-eol.pdf` — entries and structural lines that rotate through
//!   all legal forms, proving no uniform-EOL assumption anywhere.
//!
//! Every fixture must load: 4 in-use objects (1 catalog, 1 page tree, 1
//! page, 1 content stream), a 5-entry xref table (objects 0..=4, object 0
//! being the free-list head), and a resolvable `/Root` catalog.

use std::path::{Path, PathBuf};

use pdfce_core::document::Document;
use pdfce_core::object::Object;
use pdfce_core::xref;

/// A fixture path under `fixtures/synthetic/xref-eol/`.
fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/synthetic/xref-eol")
        .join(name)
}

fn bytes(name: &str) -> Vec<u8> {
    std::fs::read(fixture(name)).expect("fixture readable")
}

/// The shared contract every well-formed fixture must satisfy: the xref
/// layer sees all five entries, and the document layer resolves a proper
/// catalog with four in-use objects.
fn assert_loads_cleanly(name: &str) {
    let raw = bytes(name);

    // xref layer: 5 merged entries (objects 0..=4), object 0 free-list head.
    let loaded = xref::load_xref_chain(&raw)
        .unwrap_or_else(|e| panic!("{name}: xref chain failed to load: {e}"));
    assert_eq!(
        loaded.table.len(),
        5,
        "{name}: expected 5 xref entries (objects 0..=4)"
    );
    assert!(
        matches!(loaded.table.get(0), Some(xref::XrefEntry::Free { .. })),
        "{name}: object 0 must be the free-list head"
    );
    for num in 1..=4 {
        assert!(
            matches!(loaded.table.get(num), Some(xref::XrefEntry::InUse { .. })),
            "{name}: object {num} must be an in-use entry"
        );
    }

    // document layer: catalog resolves through /Root, page tree reachable.
    let doc = Document::from_bytes(raw)
        .unwrap_or_else(|e| panic!("{name}: Document::from_bytes failed: {e}"));
    assert_eq!(doc.object_count(), 4, "{name}: expected 4 in-use objects");
    let catalog = doc
        .catalog()
        .unwrap_or_else(|e| panic!("{name}: catalog unresolvable: {e}"));
    assert_eq!(
        catalog
            .get(b"Type")
            .and_then(Object::as_name)
            .map(|n| n.as_bytes()),
        Some(&b"Catalog"[..]),
        "{name}: /Root does not resolve to a /Catalog"
    );
    // /Pages must resolve to the page tree with /Count 1.
    let pages = catalog
        .get(b"Pages")
        .map(|p| doc.resolve(p))
        .and_then(Object::as_dict)
        .unwrap_or_else(|| panic!("{name}: /Pages unresolvable"));
    assert_eq!(
        pages.get(b"Count").and_then(Object::as_int),
        Some(1),
        "{name}: page tree /Count is not 1"
    );
}

#[test]
fn entry_eol_sp_cr_loads() {
    assert_loads_cleanly("entry-spcr.pdf");
}

#[test]
fn entry_eol_sp_lf_loads() {
    assert_loads_cleanly("entry-splf.pdf");
}

#[test]
fn entry_eol_cr_lf_loads() {
    assert_loads_cleanly("entry-crlf.pdf");
}

#[test]
fn structural_lines_bare_cr_loads() {
    assert_loads_cleanly("struct-cr.pdf");
}

#[test]
fn structural_lines_crlf_loads() {
    assert_loads_cleanly("struct-crlf.pdf");
}

#[test]
fn multi_subsection_out_of_order_loads() {
    assert_loads_cleanly("multi-subsection.pdf");
}

#[test]
fn trailing_space_before_header_eol_loads() {
    assert_loads_cleanly("trailing-space.pdf");
}

#[test]
fn old_mac_bare_cr_everywhere_loads() {
    assert_loads_cleanly("bare-cr-oldmac.pdf");
}

#[test]
fn mixed_eol_forms_load() {
    assert_loads_cleanly("mixed-eol.pdf");
}

// ---------------------------------------------------------------------------
// The WRITE side — `EOL-A1` / `EOL-A2` as operator settings (R169)
// ---------------------------------------------------------------------------
//
// Everything above is the READ side: pdfce accepts every EOL form §7.5.4
// and §7.5.1 permit. These prove the other direction — that pdfce can now
// *emit* each of §7.5.4's three permitted entry terminators and either
// answer to §7.5.5's trailing-EOL question, that each choice produces a
// file pdfce itself reloads cleanly, and (the part that matters most)
// that the DEFAULTS are byte-for-byte what pdfce emitted before the
// settings existed.
//
// Why the round trip is asserted rather than just the bytes: an entry
// terminator that changed the entry's length would still "look right" in
// a byte assertion on the last two bytes while silently breaking every
// offset in the table. Reloading is what catches that, and it is exactly
// decision 007 W10's named failure mode ("a file most readers repair
// silently and pdfce's own lenient parser will happily reload") from the
// opposite side.

use pdfce_core::settings::{TrailingEol, XrefEntryEol};
use pdfce_core::writer::{DirtySet, SaveOptions, save_full};

/// A small, well-formed classic-xref document to rewrite.
fn classic_source() -> Vec<u8> {
    bytes("entry-splf.pdf")
}

/// Every 20-byte entry line in a classic table, as raw bytes.
///
/// Located by scanning for the `xref` keyword rather than by parsing,
/// because the point is to inspect the bytes the writer actually laid
/// down — a check routed through the parser would be checking the parser.
///
/// Scanned from the END, and matching `\nxref\n` rather than bare `xref`:
/// these fixtures' own content streams draw the literal string
/// `(xref EOL fixture)`, so a forward search for four bytes finds the
/// page's text and walks off into the body. (Found the hard way; left as
/// a warning, because every PDF byte-scanner meets this eventually.)
fn classic_entries(pdf: &[u8]) -> Vec<Vec<u8>> {
    let at = pdf
        .windows(6)
        .rposition(|w| w == b"\nxref\n")
        .expect("a classic table")
        + 1;
    // Skip `xref` + its EOL + the `0 N` subsection header + its EOL.
    let mut cursor = at + 4;
    let mut newlines = 0;
    while cursor < pdf.len() && newlines < 2 {
        if pdf[cursor] == b'\n' {
            newlines += 1;
        }
        cursor += 1;
    }
    let mut out = Vec::new();
    while cursor + 20 <= pdf.len() && pdf[cursor].is_ascii_digit() {
        out.push(pdf[cursor..cursor + 20].to_vec());
        cursor += 20;
    }
    out
}

#[test]
fn the_writer_emits_every_permitted_entry_terminator_and_reloads_each() {
    for (eol, want) in [
        (XrefEntryEol::SpaceLf, &b" \n"[..]),
        (XrefEntryEol::SpaceCr, &b" \r"[..]),
        (XrefEntryEol::CrLf, &b"\r\n"[..]),
    ] {
        let doc = Document::from_bytes(classic_source()).expect("fixture loads");
        let options = SaveOptions::identity().with_xref_entry_eol(eol);
        let (out, _) = save_full(&doc, &DirtySet::empty(), &options).expect("save_full");

        let entries = classic_entries(&out);
        assert!(!entries.is_empty(), "{eol:?}: no entries found");
        for entry in &entries {
            assert_eq!(entry.len(), 20, "{eol:?}: §7.5.4's 20-byte rule broken");
            assert!(
                entry.ends_with(want),
                "{eol:?}: entry ended {:?}",
                &entry[18..]
            );
        }

        // The whole point of the 20-byte rule: every stored offset still
        // addresses what it claims to.
        let reloaded = Document::from_bytes(out).expect("pdfce reloads its own output");
        let catalog = reloaded
            .catalog()
            .unwrap_or_else(|e| panic!("{eol:?}: catalog unresolvable after rewrite: {e}"));
        assert_eq!(
            catalog
                .get(b"Type")
                .and_then(Object::as_name)
                .map(|n| n.as_bytes()),
            Some(&b"Catalog"[..]),
            "{eol:?}: rewritten file lost its catalog"
        );
    }
}

#[test]
fn the_writer_honours_both_answers_to_the_trailing_eol_question() {
    let doc = Document::from_bytes(classic_source()).expect("fixture loads");

    let (with, _) = save_full(
        &doc,
        &DirtySet::empty(),
        &SaveOptions::identity().with_trailing_eol(TrailingEol::Lf),
    )
    .expect("save_full");
    let (without, _) = save_full(
        &doc,
        &DirtySet::empty(),
        &SaveOptions::identity().with_trailing_eol(TrailingEol::None),
    )
    .expect("save_full");

    assert!(with.ends_with(b"%%EOF\n"));
    assert!(without.ends_with(b"%%EOF"));
    assert_eq!(
        with.len(),
        without.len() + 1,
        "the trailing-EOL setting must move exactly one byte"
    );
    // Both must still be a PDF. §7.5.5's `%%EOF` scan is backward from
    // the end, so an unterminated last line is the case a naive scanner
    // gets wrong.
    Document::from_bytes(without).expect("an unterminated %%EOF still loads");
}

#[test]
fn the_defaults_are_exactly_what_pdfce_emitted_before_the_settings_existed() {
    // R169's non-negotiable: adding a knob changes no observable
    // behaviour. `SaveOptions::identity()` carries the defaults, and the
    // explicit-default save must be byte-identical to it.
    let doc = Document::from_bytes(classic_source()).expect("fixture loads");
    let (implicit, _) =
        save_full(&doc, &DirtySet::empty(), &SaveOptions::identity()).expect("save_full");
    let (explicit, _) = save_full(
        &doc,
        &DirtySet::empty(),
        &SaveOptions::identity()
            .with_xref_entry_eol(XrefEntryEol::SpaceLf)
            .with_trailing_eol(TrailingEol::Lf),
    )
    .expect("save_full");
    assert_eq!(implicit, explicit, "the defaults moved");
    for entry in classic_entries(&implicit) {
        assert!(entry.ends_with(b" \n"), "default entry EOL is not `SP LF`");
    }
    assert!(
        implicit.ends_with(b"%%EOF\n"),
        "default lost its trailing EOL"
    );
}
