//! Integration tests for cross-reference RECOVERY (decision 013 Pass B).
//!
//! Pass B adds a rebuild-by-scan fallback: when a file's stored
//! cross-reference machinery cannot be parsed, pdfce reconstructs the
//! cross-reference table and trailer by scanning the whole buffer for
//! `N G obj` headers and walking recovered object streams. These tests
//! drive that path over the synthetic controls in
//! `fixtures/synthetic/xref-recover/` (generated by
//! `tools/gen-xref-recover-fixtures.py`); each is a deliberately-damaged
//! or headerless document that STRICT loading rejects.
//!
//! What is asserted, per fixture:
//! - the recoverable ones **open** via [`Document::from_bytes`], expose a
//!   [`RecoveryReport`] (never `None`), and resolve their `/Catalog`;
//! - the counted disclosure is populated (fuzzy-never-sneaky, R20);
//! - the recovered document REFUSES `save_incremental` by name and its
//!   `save_full` produces a reloadable file with a fresh valid classic xref
//!   (the recovered-base-forces-full-rewrite rule, decision 013 §9);
//! - the unrecoverable one **refuses** cleanly (no `/Catalog`), never
//!   returning a garbage document.
//!
//! Structure mirrors `tests/xref_eol.rs` (Pass A).

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::path::PathBuf;

use pdfce_core::document::{DocError, Document};
use pdfce_core::object::Object;
use pdfce_core::recover::{RecoverError, RecoveryReason, TrailerSource};
use pdfce_core::writer::{DirtySet, SaveOptions, WriteError, save_full, save_incremental};

/// Read a fixture from `fixtures/synthetic/xref-recover/`.
fn fixture(name: &str) -> Vec<u8> {
    let path: PathBuf = [
        env!("CARGO_MANIFEST_DIR"),
        "..",
        "..",
        "fixtures",
        "synthetic",
        "xref-recover",
        name,
    ]
    .iter()
    .collect();
    std::fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
}

/// Load a fixture, asserting it opened VIA RECOVERY (not the strict path)
/// and resolves to a one-page document, and return the loaded `Document`.
fn assert_recovers(name: &str) -> Document {
    let doc = Document::from_bytes(fixture(name))
        .unwrap_or_else(|e| panic!("{name} failed to recover: {e}"));
    let report = doc
        .recovery()
        .unwrap_or_else(|| panic!("{name} loaded but was NOT flagged as recovered"));
    // The disclosure must be populated: at least one object recovered.
    assert!(
        report.file_level_objects + report.objstm_objects > 0,
        "{name}: recovery report has no objects"
    );
    // The catalog must resolve — recovery refuses without one, so a loaded
    // recovered document always has it.
    let cat = doc
        .catalog()
        .unwrap_or_else(|e| panic!("{name}: catalog: {e}"));
    assert_eq!(
        cat.get(b"Type")
            .and_then(Object::as_name)
            .map(|n| n.as_bytes()),
        Some(&b"Catalog"[..]),
        "{name}: /Root is not a /Catalog"
    );
    doc
}

/// A recovered document must refuse `save_incremental` by name and produce a
/// reloadable file from `save_full` (the recovered-base rule).
fn assert_full_rewrite_only(name: &str, doc: &Document) {
    let refused = save_incremental(doc, &DirtySet::empty(), &SaveOptions::identity());
    assert!(
        matches!(refused, Err(WriteError::RecoveredBaseForbidsIncremental)),
        "{name}: save_incremental should be refused by name, got {refused:?}"
    );

    let (bytes, _report) = save_full(doc, &DirtySet::empty(), &SaveOptions::identity())
        .unwrap_or_else(|e| panic!("{name}: save_full: {e}"));
    // The rewritten file must load CLEANLY now — a fresh valid classic xref
    // means recovery does NOT fire on the second load.
    let back = Document::from_bytes(bytes).unwrap_or_else(|e| panic!("{name}: reload: {e}"));
    assert!(
        back.recovery().is_none(),
        "{name}: the full-rewrite output still triggers recovery (its xref is not clean)"
    );
    assert_eq!(
        back.object_count(),
        doc.object_count(),
        "{name}: object count changed across the recovered full rewrite"
    );
}

#[test]
fn offset_shifted_startxref_recovers() {
    let doc = assert_recovers("offset-shifted-startxref.pdf");
    let r = doc.recovery().unwrap();
    assert_eq!(r.reason, RecoveryReason::NotAnXrefSection);
    assert_eq!(r.trailer_source, TrailerSource::TrailerKeyword);
    assert_eq!(doc.object_count(), 4);
    assert_full_rewrite_only("offset-shifted-startxref.pdf", &doc);
}

#[test]
fn no_startxref_recovers() {
    let doc = assert_recovers("no-startxref.pdf");
    assert_eq!(
        doc.recovery().unwrap().reason,
        RecoveryReason::StartxrefNotFound
    );
    assert_eq!(doc.object_count(), 4);
    assert_full_rewrite_only("no-startxref.pdf", &doc);
}

#[test]
fn startxref_out_of_range_recovers() {
    let doc = assert_recovers("startxref-out-of-range.pdf");
    assert_eq!(
        doc.recovery().unwrap().reason,
        RecoveryReason::BadStartxrefOffset
    );
    assert_eq!(doc.object_count(), 4);
    assert_full_rewrite_only("startxref-out-of-range.pdf", &doc);
}

#[test]
fn xref_stream_corrupt_recovers_file_level_and_objstm() {
    let doc = assert_recovers("xref-stream-corrupt.pdf");
    let r = doc.recovery().unwrap();
    // The trailer comes from the /Type /XRef dictionary (no `trailer` kw).
    assert_eq!(r.trailer_source, TrailerSource::XrefStreamDict);
    // Object 6 is compressed in the object stream (object 5): it must be
    // recovered as a type-2 entry.
    assert!(
        r.objstm_objects >= 1,
        "expected at least one ObjStm-recovered object, got {}",
        r.objstm_objects
    );
    // Objects 1-5 + 7 file-level, 6 from the ObjStm = 7 total.
    assert_eq!(doc.object_count(), 7);
    // Object 6 (the ExtGState in the ObjStm) resolved.
    let g6 = doc
        .resolve(&Object::Reference(pdfce_core::object::ObjId::new(6, 0)))
        .as_dict()
        .cloned();
    assert!(
        g6.is_some(),
        "compressed object 6 not resolvable after recovery"
    );
    assert_full_rewrite_only("xref-stream-corrupt.pdf", &doc);
}

#[test]
fn duplicate_superseded_last_wins() {
    let doc = assert_recovers("duplicate-superseded.pdf");
    let r = doc.recovery().unwrap();
    assert!(
        r.last_wins_collisions >= 1,
        "expected a last-wins collision for the duplicated object 3"
    );
    // Last-valid-wins: the SECOND definition of object 3 governs.
    let page3 = doc
        .get(pdfce_core::object::ObjId::new(3, 0))
        .expect("object 3 present");
    let note = page3
        .value
        .as_dict()
        .and_then(|d| d.get(b"Note"))
        .and_then(|o| match o {
            Object::String(s) => Some(s.clone()),
            _ => None,
        });
    assert_eq!(
        note.as_deref(),
        Some(&b"SECOND"[..]),
        "recovery picked the wrong revision of the duplicated object"
    );
    assert_full_rewrite_only("duplicate-superseded.pdf", &doc);
}

#[test]
fn offset_start_recovers_header_independent() {
    let doc = assert_recovers("offset-start.pdf");
    let r = doc.recovery().unwrap();
    assert_eq!(r.reason, RecoveryReason::MissingHeader);
    assert!(
        r.offset_start,
        "offset_start flag should be set for leading junk"
    );
    // Version was still detected by the whole-buffer %PDF- scan.
    assert_eq!(doc.version().to_string(), "1.7");
    assert_eq!(doc.object_count(), 4);
    assert_full_rewrite_only("offset-start.pdf", &doc);
}

/// The LF→CRLF conversion shape — the cause behind 337 of the 341
/// corpus files that were unopenable with `BadContents`.
///
/// Both halves of the damage are asserted: the object count proves the
/// content stream was NOT dropped by confirmation (it was, before the
/// `StreamLengthPolicy::RecoverFromEndstream` fix, leaving 3 of 4), and
/// `stream_lengths_recovered` proves the repair is counted for disclosure
/// rather than applied silently. Extracting the text proves the recovered
/// extent is the real payload and not a truncation — a file that "opens"
/// as a blank page would satisfy every structural assertion above and
/// still be a non-fix.
#[test]
fn crlf_shifted_lengths_recovers_the_content_stream() {
    let doc = assert_recovers("crlf-shifted-lengths.pdf");
    let r = doc.recovery().unwrap();
    assert_eq!(r.reason, RecoveryReason::NotAnXrefSection);
    assert_eq!(
        r.file_level_objects, 4,
        "the content stream must survive confirmation despite its stale /Length"
    );
    assert_eq!(
        r.stream_lengths_recovered, 1,
        "the one re-derived extent is counted, not silently absorbed"
    );
    assert_eq!(doc.object_count(), 4);

    // The page resolves to a real content stream, and that stream holds
    // the real text.
    let pages = pdfce_core::page_tree::pages(&doc).expect("page tree");
    assert_eq!(pages.len(), 1);
    assert_eq!(pages[0].contents.len(), 1);
    assert_eq!(
        pages[0].contents_unresolved, 0,
        "nothing degraded — the object was genuinely recovered"
    );
    let text = pdfce_core::text_extract::extract_document(
        &doc,
        &pdfce_core::text_extract::ExtractOptions::default(),
    )
    .expect("extract");
    assert!(
        text.plain_text().contains("crlf shifted lengths"),
        "recovered stream must carry the real content, got {:?}",
        text.plain_text()
    );

    assert_full_rewrite_only("crlf-shifted-lengths.pdf", &doc);
}

/// A dangling single `/Contents` reference on a file whose cross-reference
/// table is VALID: it loads on the strict path (no recovery), yields an
/// empty page, discloses the omission, and — the §5 point — still saves
/// byte-identically, because degrading a `/Contents` element changes
/// nothing about the bytes pdfce is holding.
#[test]
fn dangling_contents_degrades_on_the_strict_path_and_round_trips() {
    let source = fixture("dangling-contents.pdf");
    let doc = Document::from_bytes(source.clone()).expect("must load");
    assert!(
        doc.recovery().is_none(),
        "this fixture's xref is valid — it must NOT take the recovery path"
    );

    let pages = pdfce_core::page_tree::pages(&doc).expect("a dangling /Contents is not fatal");
    assert_eq!(pages.len(), 1);
    assert!(
        pages[0].contents.is_empty(),
        "Table 30: absent /Contents = an empty page"
    );
    assert_eq!(
        pages[0].contents_unresolved, 1,
        "the omission is disclosed, so an empty page is distinguishable from a blank one"
    );

    // ARCHITECTURE.md §5: nothing was touched, so an empty-dirty-set
    // incremental save must reproduce the source bytes exactly.
    let (bytes, _report) =
        save_incremental(&doc, &DirtySet::empty(), &SaveOptions::identity()).expect("save");
    assert_eq!(
        bytes, source,
        "a document that opens via a degraded /Contents must still round-trip byte-identically"
    );
}

/// The array form: the dangling element is dropped, the two real streams
/// survive **in order**, and the count discloses the one omission.
#[test]
fn dangling_contents_array_keeps_the_surviving_streams_in_order() {
    let source = fixture("dangling-contents-array.pdf");
    let doc = Document::from_bytes(source.clone()).expect("must load");
    assert!(doc.recovery().is_none());

    let pages = pdfce_core::page_tree::pages(&doc).expect("must walk");
    assert_eq!(pages.len(), 1);
    let nums: Vec<u32> = pages[0].contents.iter().map(|id| id.num).collect();
    assert_eq!(
        nums,
        vec![4, 6],
        "surviving elements keep their order — Table 30 concatenates them"
    );
    assert_eq!(pages[0].contents_unresolved, 1);

    let (bytes, _report) =
        save_incremental(&doc, &DirtySet::empty(), &SaveOptions::identity()).expect("save");
    assert_eq!(bytes, source, "\u{a7}5 holds for the array form too");
}

#[test]
fn unrecoverable_no_catalog_refuses_clean() {
    let err = Document::from_bytes(fixture("unrecoverable-no-catalog.pdf")).unwrap_err();
    assert!(
        matches!(err, DocError::Recovery(RecoverError::NoCatalog)),
        "expected a clean NoCatalog refusal, got {err:?}"
    );
}
