#!/usr/bin/env python3
"""Regenerate fixtures/synthetic/forms-xobject/ — pages whose content is wrapped
in form XObjects, which is the shape that made objects unclickable.

WHY THIS EXISTS
---------------
`decompose_page` used to emit a form XObject as ONE opaque object bounded by its
`/BBox` and never enter it. On a page whose visible body is wrapped in a form —
what SolidWorks emits per orthographic view, and what a great many print files
emit per panel — that means the form is an object sitting in paint order above
everything drawn before it, and a hit test answers every click, anywhere, with
the form.

The operator's report, relayed from the GUI project: *"when I click on one of
the objects all I get is the page selected."* He was selecting a real object. It
was a form.

**No committed fixture had a form XObject at all**, which is why nothing caught
it. Every vector fixture in this repository draws straight onto the page.

WHAT THE FIXTURES ARE
---------------------
Four single-page PDFs, each 200 x 200 pt, each isolating one property:

| file | shape | what it pins |
|---|---|---|
| `page-sized-form.pdf` | one page-sized form holding **three** separate squares | the operator's case: 1 flat object, 3 leaves |
| `nested-forms.pdf` | form A holds form B holds one square | containment depth 2, and that an intermediate form is NOT itself a leaf |
| `self-referential-form.pdf` | a form that invokes **itself** | the cycle guard: the walk terminates and says so |
| `shared-form-twice.pdf` | one form invoked **twice**, at different offsets | the same form's leaves appear once per invocation, in different places, with the same containment id |

★ `shared-form-twice.pdf` is the one that will surprise a reader, so it is worth
stating: a form invoked twice contributes its contents twice, at two different
page positions, and both leaves name the same form object. That is not a bug in
the walk — it is what the page actually draws, and it is exactly the situation
that makes editing a leaf inside a shared form change every invocation
(`ARCHITECTURE.md` §12 decision 076).

★★ `self-referential-form.pdf` is NOT a corrupt file. ISO 32000-1 §8.10.1 does
not forbid a form invoking itself, and no rule anywhere makes it invalid — it is
simply unbounded to a naive walker. A renderer or decomposer that hangs on it
has a defect; one that refuses the whole page has a different defect. The right
answer is to descend once, notice the repeat, stop, and count it.

PROVENANCE
----------
Authored here, byte by byte, from ISO 32000-1's own object syntax. No
third-party PDF is copied, adapted or consulted (`docs/LEGAL.md` §5). The files
are small enough to read in a text editor.

This script is NOT part of the build and is not a workspace member.

USAGE
-----
    python tools/gen-form-recursion-fixtures.py
"""

from __future__ import annotations

import pathlib

OUT = (
    pathlib.Path(__file__).resolve().parent.parent
    / "fixtures"
    / "synthetic"
    / "forms-xobject"
)


def assemble(objects: list[bytes]) -> bytes:
    """Wrap emitted object bodies in a header, xref table and trailer.

    Hand-rolled rather than delegated to `pdfce-cli` on purpose: a fixture
    generated by the program under test cannot falsify that program.
    """
    out = bytearray(b"%PDF-1.7\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for i, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += str(i).encode() + b" 0 obj\n" + body + b"\nendobj\n"
    startxref = len(out)
    n = len(objects) + 1
    out += b"xref\n0 " + str(n).encode() + b"\n0000000000 65535 f \n"
    for off in offsets[1:]:
        out += f"{off:010d} 00000 n \n".encode()
    out += (
        b"trailer\n<< /Size " + str(n).encode() + b" /Root 1 0 R >>\n"
        b"startxref\n" + str(startxref).encode() + b"\n%%EOF\n"
    )
    return bytes(out)


def stream(dict_body: bytes, data: bytes) -> bytes:
    return (
        b"<< " + dict_body + b" /Length " + str(len(data)).encode() + b" >>\nstream\n"
        + data
        + b"\nendstream"
    )


def page_sized_form() -> bytes:
    """One page-sized form holding three separate squares.

    The operator's case in miniature: the flat list has ONE object (the form),
    and everything he would want to click is inside it.
    """
    form_content = (
        b"1 0 0 RG 0 0 1 rg\n"
        b"10 10 40 40 re f\n"
        b"80 80 40 40 re f\n"
        b"150 150 40 40 re f\n"
    )
    page_content = b"q /Fm0 Do Q\n"
    return assemble([
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] "
        b"/Resources << /XObject << /Fm0 5 0 R >> >> /Contents 4 0 R >>",
        stream(b"", page_content),
        stream(b"/Type /XObject /Subtype /Form /BBox [0 0 200 200]", form_content),
    ])


def nested_forms() -> bytes:
    """Form A holds form B holds one square — containment depth 2."""
    inner = b"0 1 0 rg\n20 20 30 30 re f\n"
    outer = b"q 1 0 0 1 50 50 cm /Fm1 Do Q\n"
    page = b"q /Fm0 Do Q\n"
    return assemble([
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] "
        b"/Resources << /XObject << /Fm0 5 0 R >> >> /Contents 4 0 R >>",
        stream(b"", page),
        stream(
            b"/Type /XObject /Subtype /Form /BBox [0 0 200 200] "
            b"/Resources << /XObject << /Fm1 6 0 R >> >>",
            outer,
        ),
        stream(b"/Type /XObject /Subtype /Form /BBox [0 0 100 100]", inner),
    ])


def self_referential_form() -> bytes:
    """A form that invokes itself.

    §8.10.1 does not forbid this and nothing makes the file invalid. It is
    simply unbounded to a naive walker, so it is the cycle guard's fixture.
    """
    form = b"1 0 0 rg\n10 10 20 20 re f\nq 1 0 0 1 20 20 cm /Self Do Q\n"
    page = b"q /Self Do Q\n"
    return assemble([
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] "
        b"/Resources << /XObject << /Self 5 0 R >> >> /Contents 4 0 R >>",
        stream(b"", page),
        # ★ The form's OWN /Resources names itself, which is what closes the
        # loop. Without this the inner `Do` would resolve against the page's
        # resources -- which also names it, so the cycle exists either way;
        # declaring it here makes the file's intent unambiguous to a reader.
        stream(
            b"/Type /XObject /Subtype /Form /BBox [0 0 200 200] "
            b"/Resources << /XObject << /Self 5 0 R >> >>",
            form,
        ),
    ])


def shared_form_twice() -> bytes:
    """One form invoked twice, at different offsets."""
    form = b"0 0 1 rg\n0 0 30 30 re f\n"
    page = b"q 1 0 0 1 10 10 cm /Fm0 Do Q\nq 1 0 0 1 120 120 cm /Fm0 Do Q\n"
    return assemble([
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] "
        b"/Resources << /XObject << /Fm0 5 0 R >> >> /Contents 4 0 R >>",
        stream(b"", page),
        stream(b"/Type /XObject /Subtype /Form /BBox [0 0 30 30]", form),
    ])


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for name, data in {
        "page-sized-form.pdf": page_sized_form(),
        "nested-forms.pdf": nested_forms(),
        "self-referential-form.pdf": self_referential_form(),
        "shared-form-twice.pdf": shared_form_twice(),
    }.items():
        (OUT / name).write_bytes(data)
        print(f"wrote {OUT / name}  ({len(data)} bytes)")


if __name__ == "__main__":
    main()
