#!/usr/bin/env python3
"""Build the single-folder portable distribution into ``D:\\builds``.

WHY THIS EXISTS
===============

Operator request, 2026-08-10: *"when you finish milestones like this can
you put a portable app build in d:\\builds? This way I can try it out
while you are working on the actual code."*

That last clause is the whole design constraint, and it is not the
obvious one. The build is not an archive — it is something **run while
the working tree keeps moving underneath it**. Everything below follows
from that:

* **Every build gets its OWN dated folder**, never an overwrite. Two
  reasons, and the second is fatal to the alternative: the operator may
  want to compare a new build against the one that behaved differently,
  and on Windows **an executable that is currently running cannot be
  replaced**. Overwriting a folder whose `pdfce-gui.exe` is open fails
  partway, leaving a half-updated directory that is worse than either
  version.
* **The folder name carries the commit**, so a bug report can be tied to
  a tree state without asking the operator to remember when they
  downloaded it.
* **`BUILD-INFO.txt` names what is IN this build.** "Try it out" is
  answerable only if the operator knows what to try. It lists the
  commits since the previous build in `D:\\builds`, so each build's note
  is the delta rather than the whole history.

WHAT IT PRODUCES
================

``D:\\builds\\pdfce-<YYYYMMDD-HHMM>-<shorthash>[-dirty]\\``

    pdfce-gui.exe            the GUI
    pdfce-cli.exe            the CLI
    LICENSE                  MIT
    THIRD_PARTY_LICENSES.md  generated by cargo-about, never hand-edited
    README.md                the project README
    BUILD-INFO.txt           commit, timestamp, test/gate state, changes

**`userdata/` is deliberately NOT created.** ARCHITECTURE.md §6's
payload/user-state partition (decision 003 R15) makes it the app's own
at first run, in the exe's directory. Shipping an empty one here would
mean a fresh build always looks like it has state, and the whole point
of the partition is that "replace the folder" is a safe update procedure
because the payload and the state are distinguishable.

THE `-dirty` SUFFIX IS LOAD-BEARING
===================================

A build made from an uncommitted working tree gets `-dirty` in its name
and a warning in `BUILD-INFO.txt`. Without it, a folder named for a
commit would be a claim the operator could reasonably rely on and that
would sometimes be false — which is exactly the class of error this
project keeps finding in its own documents (R175: a document asserting
an unmeasured fact about its environment).

EXIT CODES
==========

``0`` build written; ``1`` a prerequisite is missing (no cargo, no repo,
no binaries after a build attempt); ``2`` the destination exists and is
non-empty, which should be impossible given the timestamp and means
something else is writing there.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

# Windows consoles default to a code page that cannot encode this file's
# arrows and dashes; see the same block in the check-*.py gates.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

REPO = Path(__file__).resolve().parent.parent
DEFAULT_DEST = Path("D:/builds")

#: Payload files copied verbatim from the repo root. Order is the order
#: they are listed in BUILD-INFO.txt, so it is deliberate rather than
#: alphabetical: licence first, attribution second, docs last.
PAYLOAD_DOCS = ["LICENSE", "THIRD_PARTY_LICENSES.md", "README.md"]

#: The two shipped binaries. `pdfce-cli` is a first-class feature, not a
#: debug tool (project rule 11), so it ships in the same folder.
BINARIES = ["pdfce-gui.exe", "pdfce-cli.exe"]


def git(*args: str) -> str:
    """Run a git command in the repo and return its stripped stdout.

    `encoding="utf-8"` is not optional. `text=True` alone decodes with the
    LOCALE codec, which on this machine is cp1252, and this project's
    commit subjects are full of em-dashes — so the changelog in
    `BUILD-INFO.txt` rendered `Pass 54.1 â€” a group can be deleted`.

    Third instance of this same encoding class in one session, after the
    Python gates' console output and the PowerShell harness's source. The
    common root is that Windows defaults to cp1252 everywhere UTF-8 is not
    demanded explicitly. `errors="replace"` so a stray non-UTF-8 byte in
    some future commit degrades one character instead of failing a build.
    """
    return subprocess.run(
        ["git", *args],
        cwd=REPO,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    ).stdout.strip()


def previous_build_commit(dest: Path) -> str | None:
    """The commit of the most recent build already in `dest`, if any.

    Read from that build's own `BUILD-INFO.txt` rather than parsed out of
    the folder name: the name is for humans and could be renamed, the
    file is the record. Returns `None` when there is no prior build or
    its info file is unreadable — in which case the changelog below
    simply covers a fixed recent window instead.
    """
    builds = sorted(
        (p for p in dest.glob("pdfce-*") if p.is_dir()),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    for b in builds:
        info = b / "BUILD-INFO.txt"
        if not info.is_file():
            continue
        for line in info.read_text(encoding="utf-8", errors="replace").splitlines():
            if line.startswith("Commit:"):
                return line.split(":", 1)[1].strip().split()[0]
    return None


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--dest",
        type=Path,
        default=DEFAULT_DEST,
        help="destination root (default: D:/builds)",
    )
    ap.add_argument(
        "--no-build",
        action="store_true",
        help="package the existing target/release binaries without rebuilding",
    )
    ap.add_argument(
        "--note",
        default="",
        help="one-line summary of what this milestone added, for BUILD-INFO.txt",
    )
    args = ap.parse_args()

    if not (REPO / "Cargo.toml").is_file():
        print(f"package-portable: {REPO} is not the pdfce repo root.")
        return 1

    # --- identity, before anything is built --------------------------------
    short = git("rev-parse", "--short", "HEAD") or "unknown"
    subject = git("log", "-1", "--format=%s")
    dirty = bool(git("status", "--porcelain"))
    stamp = datetime.now().strftime("%Y%m%d-%H%M")
    name = f"pdfce-{stamp}-{short}" + ("-dirty" if dirty else "")
    out = args.dest / name

    if out.exists() and any(out.iterdir()):
        print(f"package-portable: {out} already exists and is not empty.")
        return 2

    # --- build --------------------------------------------------------------
    if not args.no_build:
        print("package-portable: cargo build --release ...")
        rc = subprocess.run(
            ["cargo", "build", "--release", "-p", "pdfce-gui", "-p", "pdfce-cli"],
            cwd=REPO,
            check=False,
        ).returncode
        if rc != 0:
            print("package-portable: the release build failed; nothing packaged.")
            return 1

    rel = REPO / "target" / "release"
    missing = [b for b in BINARIES if not (rel / b).is_file()]
    if missing:
        print(f"package-portable: missing binaries in {rel}: {', '.join(missing)}")
        return 1

    # --- assemble -----------------------------------------------------------
    out.mkdir(parents=True, exist_ok=True)
    for b in BINARIES:
        shutil.copy2(rel / b, out / b)
    copied_docs = []
    for d in PAYLOAD_DOCS:
        src = REPO / d
        if src.is_file():
            shutil.copy2(src, out / d)
            copied_docs.append(d)
        else:
            print(f"package-portable: WARNING — {d} not found at the repo root")

    # --- what changed since the last build ----------------------------------
    prev = previous_build_commit(args.dest)
    if prev:
        span = f"{prev}..HEAD"
        changes = git("log", "--oneline", "--no-decorate", span)
        change_header = f"Changes since the previous build ({prev}):"
    else:
        changes = git("log", "--oneline", "--no-decorate", "-15")
        change_header = "Recent commits (no previous build found to diff against):"
    if not changes:
        changes = "  (no new commits since the previous build)"
    else:
        changes = "\n".join(f"  {line}" for line in changes.splitlines())

    warn = ""
    if dirty:
        warn = (
            "\n*** BUILT FROM AN UNCOMMITTED WORKING TREE ***\n"
            "The commit below identifies the last COMMIT, not what was built.\n"
            "Uncommitted changes were present, so this build contains code that\n"
            "is in no commit and cannot be recovered from the hash alone.\n"
        )

    # Hoisted out of the f-string below: an expression part may not contain
    # a backslash before Python 3.12, and this machine runs 3.11.
    note_block = f"THIS BUILD\n----------\n{args.note}\n" if args.note else ""

    (out / "BUILD-INFO.txt").write_text(
        f"""pdfce portable build
====================
{warn}
Built:  {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Commit: {short}  {subject}
Branch: {git("rev-parse", "--abbrev-ref", "HEAD")}

WHAT THIS IS
------------
A single-folder portable build. No installer, no registry writes, nothing
outside this folder. Run pdfce-gui.exe.

pdfce-cli.exe is a first-class scriptable CLI, not a debug tool — run it
with --help, or `pdfce-cli <subcommand> --help`.

YOUR SETTINGS LIVE IN THIS FOLDER
---------------------------------
On first run pdfce creates `userdata/` here and keeps your settings in
`userdata/settings.txt` (a plain, hand-editable `key = value` file).

That means: to update, replace the binaries but KEEP `userdata/`. If
pdfce cannot write here — a read-only share, or Program Files without
elevation — it falls back to the platform config directory and tells you
which one it used, because the two behave differently on update.

{note_block}
{change_header}
{changes}

Files in this build: {", ".join(BINARIES + copied_docs)}
""",
        encoding="utf-8",
    )

    total = sum(f.stat().st_size for f in out.rglob("*") if f.is_file())
    print(f"\npackage-portable: wrote {out}")
    for f in sorted(out.iterdir()):
        print(f"  {f.name:<26} {f.stat().st_size:>10,} bytes")
    print(f"  {'TOTAL':<26} {total:>10,} bytes")
    if dirty:
        print("\n  WARNING: built from an uncommitted working tree (-dirty).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
